### ISSUE TITLE
Plugin arxiu: Error de ClassCastException al crear un nou expedient

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/pluginsib#39]
Al crear un expedient dona el següent error:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at es.caib.plugins.arxiu.caib.ArxiuConversioHelper.toExpedientMetadades(ArxiuConversioHelper.java:317)
        at es.caib.plugins.arxiu.caib.ArxiuConversioHelper.fileNodeToExpedient(ArxiuConversioHelper.java:89)
        at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.expedientCrear(ArxiuPluginCaib.java:176)

**Comment by josepg-limit** [comment]
Aquest error només es dona si s'especifica un valor de la metadada classificacio que només contengui nombres.

**Comment by cfuster-fundaciobit** [comment]
El tiquet s'ha mogut a: https://github.com/GovernIB/pluginsib-arxiu/issues/3
